# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'classify.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import *
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import cv2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import QPalette, QColor, QMovie

import show
from predicted import predict_
from PIL import Image
from PyQt5.QtGui import *
import math
from show import *


class Ui_MainWindow(QMainWindow):
    group_num = 1  # 图像列表当前组数（页数）
    list_files = []  # 图像文件路径集
    signal_page = pyqtSignal(int)  # 页数信号
    flag = 0
    file_list = []

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 1000)  # 676, 491
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Rec2 = QtWidgets.QLabel(self.centralwidget)
        self.Rec2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Rec2.setStyleSheet('font:30px;')
        self.Rec2.setObjectName("Rec2")
        self.gridLayout_2.addWidget(self.Rec2, 3, 0, 1, 1)
        self.run = QtWidgets.QPushButton(self.centralwidget)
        self.run.setStyleSheet('font:30px;')
        self.run.setObjectName("run")
        self.gridLayout_2.addWidget(self.run, 1, 1, 1, 1)
        self.acc2 = QtWidgets.QLabel(self.centralwidget)
        self.acc2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.acc2.setStyleSheet('font:30px;')
        self.acc2.setObjectName("acc2")
        self.gridLayout_2.addWidget(self.acc2, 3, 1, 1, 1)
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.result_label.setStyleSheet('font:30px;')
        self.result_label.setObjectName("result_label")
        self.gridLayout_2.addWidget(self.result_label, 2, 1, 1, 1)
        self.select_picture = QtWidgets.QPushButton(self.centralwidget)
        self.select_picture.setStyleSheet('font:30px;')
        self.select_picture.setObjectName("select_picture")
        self.gridLayout_2.addWidget(self.select_picture, 1, 0, 1, 1)
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setMaximumSize(QtCore.QSize(16777215, 30))
        self.result.setStyleSheet('font:30px;')
        self.result.setObjectName("result")
        self.gridLayout_2.addWidget(self.result, 2, 0, 1, 1)
        self.one_picture = QtWidgets.QLabel(self.centralwidget)
        self.one_picture.setObjectName("one_picture")
        self.one_picture.setMinimumSize(QtCore.QSize(0, 50))
        self.gridLayout_2.addWidget(self.one_picture, 0, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_2, 2, 2, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.picture1_p = QtWidgets.QLabel(self.centralwidget)
        self.picture1_p.setMaximumSize(QtCore.QSize(16777215, 30))
        self.picture1_p.setStyleSheet('font:30px;')
        self.picture1_p.setObjectName("picture1_p")
        self.gridLayout_5.addWidget(self.picture1_p, 2, 1, 1, 1)
        self.picture1_t = QtWidgets.QLabel(self.centralwidget)
        self.picture1_t.setMaximumSize(QtCore.QSize(16777215, 30))
        self.picture1_t.setStyleSheet("color:green;font:30px;")
        self.picture1_t.setObjectName("picture1_t")
        self.gridLayout_5.addWidget(self.picture1_t, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_14.setStyleSheet('font:30px;')
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 2, 0, 1, 1)
        self.picture1 = QtWidgets.QLabel(self.centralwidget)
        self.picture1.setMinimumSize(QtCore.QSize(0, 50))
        self.picture1.setSizeIncrement(QtCore.QSize(0, 0))
        self.picture1.setBaseSize(QtCore.QSize(0, 0))
        self.picture1.setObjectName("picture1")
        self.gridLayout_5.addWidget(self.picture1, 0, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_8.setStyleSheet('font:30px;')
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.picture2_p = QtWidgets.QLabel(self.centralwidget)
        self.picture2_p.setMaximumSize(QtCore.QSize(16777215, 30))
        self.picture2_p.setStyleSheet('font:30px;')
        self.picture2_p.setObjectName("picture2_p")
        self.gridLayout_6.addWidget(self.picture2_p, 2, 1, 1, 1)
        self.picture2_t = QtWidgets.QLabel(self.centralwidget)
        self.picture2_t.setMaximumSize(QtCore.QSize(16777215, 30))
        self.picture2_t.setStyleSheet("color:green;font:30px;")
        self.picture2_t.setObjectName("picture2_t")
        self.gridLayout_6.addWidget(self.picture2_t, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_19.setStyleSheet('font:30px;')
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 2, 0, 1, 1)
        self.picture2 = QtWidgets.QLabel(self.centralwidget)
        self.picture2.setMinimumSize(QtCore.QSize(0, 50))
        self.picture2.setSizeIncrement(QtCore.QSize(0, 0))
        self.picture2.setBaseSize(QtCore.QSize(0, 0))
        self.picture2.setObjectName("picture2")
        self.gridLayout_6.addWidget(self.picture2, 0, 0, 1, 2)
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_20.setStyleSheet('font:30px;')
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_6, 0, 1, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.picture3_p = QtWidgets.QLabel(self.centralwidget)
        self.picture3_p.setMaximumSize(QtCore.QSize(16777215, 30))
        self.picture3_p.setStyleSheet('font:30px;')
        self.picture3_p.setObjectName("picture3_p")
        self.gridLayout_7.addWidget(self.picture3_p, 2, 1, 1, 1)
        self.picture3_t = QtWidgets.QLabel(self.centralwidget)
        self.picture3_t.setMaximumSize(QtCore.QSize(16777215, 30))
        self.picture3_t.setStyleSheet("color:green;font:30px;")
        self.picture3_t.setObjectName("picture3_t")
        self.gridLayout_7.addWidget(self.picture3_t, 1, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_23.setStyleSheet('font:30px;')
        self.label_23.setObjectName("label_23")
        self.gridLayout_7.addWidget(self.label_23, 2, 0, 1, 1)
        self.picture3 = QtWidgets.QLabel(self.centralwidget)
        self.picture3.setMinimumSize(QtCore.QSize(0, 50))
        self.picture3.setSizeIncrement(QtCore.QSize(0, 0))
        self.picture3.setBaseSize(QtCore.QSize(0, 0))
        self.picture3.setObjectName("picture3")
        self.gridLayout_7.addWidget(self.picture3, 0, 0, 1, 2)
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_24.setStyleSheet('font:30px;')
        self.label_24.setObjectName("label_24")
        self.gridLayout_7.addWidget(self.label_24, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_7, 1, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.picture4_p = QtWidgets.QLabel(self.centralwidget)
        self.picture4_p.setMaximumSize(QtCore.QSize(16777215, 30))
        self.picture4_p.setStyleSheet('font:30px;')
        self.picture4_p.setObjectName("picture4_p")
        self.gridLayout_8.addWidget(self.picture4_p, 2, 1, 1, 1)
        self.picture4_t = QtWidgets.QLabel(self.centralwidget)
        self.picture4_t.setMaximumSize(QtCore.QSize(16777215, 30))
        self.picture4_t.setStyleSheet("color:green;font:30px;")
        self.picture4_t.setObjectName("picture4_t")
        self.gridLayout_8.addWidget(self.picture4_t, 1, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_31.setStyleSheet('font:30px;')
        self.label_31.setObjectName("label_31")
        self.gridLayout_8.addWidget(self.label_31, 2, 0, 1, 1)
        self.picture4 = QtWidgets.QLabel(self.centralwidget)
        self.picture4.setMinimumSize(QtCore.QSize(0, 50))
        self.picture4.setSizeIncrement(QtCore.QSize(0, 0))
        self.picture4.setBaseSize(QtCore.QSize(0, 0))
        self.picture4.setObjectName("picture4")
        self.gridLayout_8.addWidget(self.picture4, 0, 0, 1, 2)
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_32.setStyleSheet('font:30px;')
        self.label_32.setObjectName("label_32")
        self.gridLayout_8.addWidget(self.label_32, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_8, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 1, 3, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 3, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.previous_page = QtWidgets.QPushButton(self.centralwidget)
        self.previous_page.setStyleSheet('font:30px;')
        self.previous_page.setObjectName("previous_page")
        self.gridLayout_3.addWidget(self.previous_page, 1, 0, 1, 2)
        self.Rec1 = QtWidgets.QLabel(self.centralwidget)
        self.Rec1.setMinimumSize(QtCore.QSize(0, 30))
        self.Rec1.setStyleSheet('font:30px;')
        self.Rec1.setObjectName("Rec1")
        self.gridLayout_3.addWidget(self.Rec1, 4, 0, 2, 1)
        self.acc1 = QtWidgets.QLabel(self.centralwidget)
        self.acc1.setMinimumSize(QtCore.QSize(0, 30))
        self.acc1.setStyleSheet('font:30px;')
        self.acc1.setObjectName("acc1")
        self.gridLayout_3.addWidget(self.acc1, 4, 1, 2, 1)
        self.show = QtWidgets.QPushButton(self.centralwidget)
        self.show.setStyleSheet('font:30px;')
        self.show.setObjectName("show")
        self.gridLayout_3.addWidget(self.show, 0, 0, 1, 2)
        self.next_page = QtWidgets.QPushButton(self.centralwidget)
        self.next_page.setStyleSheet('font:30px;')
        self.next_page.setObjectName("next_page")
        self.gridLayout_3.addWidget(self.next_page, 2, 0, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_3.addItem(spacerItem5, 3, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 2, 2, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem6, 0, 3, 4, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 676, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Rec2.setText(_translate("MainWindow", "类别概率："))
        self.run.setText(_translate("MainWindow", "单张图像预测"))
        self.acc2.setText(_translate("MainWindow", ""))
        self.result_label.setText(_translate("MainWindow", ""))
        self.select_picture.setText(_translate("MainWindow", "选择图片"))
        self.result.setText(_translate("MainWindow", "识别结果："))
        self.one_picture.setText(_translate("MainWindow", ""))
        self.picture1_p.setText(_translate("MainWindow", ""))
        self.picture1_t.setText(_translate("MainWindow", ""))
        self.label_14.setText(_translate("MainWindow", "Predict Label:"))
        self.picture1.setText(_translate("MainWindow", ""))
        self.label_8.setText(_translate("MainWindow", "True Label:"))
        self.picture2_p.setText(_translate("MainWindow", ""))
        self.picture2_t.setText(_translate("MainWindow", ""))
        self.label_19.setText(_translate("MainWindow", "Predict Label:"))
        self.picture2.setText(_translate("MainWindow", ""))
        self.label_20.setText(_translate("MainWindow", "True Label:"))
        self.picture3_p.setText(_translate("MainWindow", ""))
        self.picture3_t.setText(_translate("MainWindow", ""))
        self.label_23.setText(_translate("MainWindow", "Predict Label:"))
        self.picture3.setText(_translate("MainWindow", ""))
        self.label_24.setText(_translate("MainWindow", "True Label:"))
        self.picture4_p.setText(_translate("MainWindow", ""))
        self.picture4_t.setText(_translate("MainWindow", ""))
        self.label_31.setText(_translate("MainWindow", "Predict Label:"))
        self.picture4.setText(_translate("MainWindow", ""))
        self.label_32.setText(_translate("MainWindow", "True Label:"))
        self.previous_page.setText(_translate("MainWindow", "上一页"))
        self.Rec1.setText(_translate("MainWindow", "识别准确率："))
        self.acc1.setText(_translate("MainWindow", ""))
        self.show.setText(_translate("MainWindow", "多张图像预测"))
        self.next_page.setText(_translate("MainWindow", "下一页"))

    def show_pic(self):
        global acc1
        global pre
        global tru
        acc1, pre, tru = show.show_pic_acc()
        self.acc1.setText(str(acc1))
        self.get_files('F:/1/emo/model_pic')
        self.show_images_list(0)

    def openimage(self):
        global fname
        imgName, imgType = QFileDialog.getOpenFileName(self, "选择图片", "", "*.jpg;;*.png;;All Files(*)")
        jpg = QPixmap(imgName).scaled(self.one_picture.width(), self.one_picture.height())
        self.one_picture.setPixmap(jpg)
        fname = imgName
        # print("open")

    def model_run(self):
        global fname
        file_name = str(fname)
        img = Image.open(file_name)
        a, b = predict_(img)
        b = '{:.2f}'.format(b)
        self.result_label.setText(a)
        self.acc2.setText(str(b))
        # print("run")

    def get_files(self, dir):  # 储存当前页需加载的图像路径
        for file in os.listdir(path=dir):  # 读取图像路径
            if file.endswith('jpg') or file.endswith('png'):
                self.list_files.append(dir + "/" + file)
        self.file_list = [self.list_files[i:i + 4] for i in range(0, len(self.list_files), 4)]

    def show_images_list(self, num):  # 加载图像列表
        if self.flag == 0 and num == -1:
            QMessageBox.about(self, "Remind", "This is the first page!")
        elif self.flag == len(self.file_list) - 1 and num == 1:
            QMessageBox.about(self, "Remind", "No more image! ")
        elif 0 <= self.flag <= len(self.file_list):
            self.flag += num
            jpg = QPixmap(self.file_list[self.flag][0])
            self.picture1.setPixmap(jpg)
            self.picture1_p.setText(pre[self.flag * 4])
            self.picture1_t.setText(tru[self.flag * 4])
            if (pre[self.flag * 4] != tru[self.flag * 4]):
                self.picture1_p.setStyleSheet('color: red;font:30px;')
            else:
                self.picture1_p.setStyleSheet('color: green;font:30px;')


            jpg = QPixmap(self.file_list[self.flag][1])
            self.picture2.setPixmap(jpg)
            self.picture2_p.setText(pre[self.flag * 4 + 1])
            self.picture2_t.setText(tru[self.flag * 4 + 1])
            if (pre[self.flag * 4 + 1] != tru[self.flag * 4 + 1]):
                self.picture2_p.setStyleSheet('color: red;font:30px;')
            else:
                self.picture2_p.setStyleSheet('color: green;font:30px;')

            jpg = QPixmap(self.file_list[self.flag][2])
            self.picture3.setPixmap(jpg)
            self.picture3_p.setText(pre[self.flag * 4 + 2])
            self.picture3_t.setText(tru[self.flag * 4 + 2])
            if (pre[self.flag * 4 + 2] != tru[self.flag * 4 + 2]):
                self.picture3_p.setStyleSheet('color: red;font:30px;')
            else:
                self.picture3_p.setStyleSheet('color: green;font:30px;')


            jpg = QPixmap(self.file_list[self.flag][3])
            self.picture4.setPixmap(jpg)
            self.picture4_p.setText(pre[self.flag * 4 + 3])
            self.picture4_t.setText(tru[self.flag * 4 + 3])
            if (pre[self.flag * 4 + 3] != tru[self.flag * 4 + 3]):
                self.picture4_p.setStyleSheet('color: red;font:30px;')
            else:
                self.picture4_p.setStyleSheet('color: green;font:30px;')



if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    widgets = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(widgets)
    widgets.show()
    ui.show.clicked.connect(lambda: ui.show_pic())
    ui.select_picture.clicked.connect(lambda: ui.openimage())
    ui.run.clicked.connect(lambda: ui.model_run())
    ui.previous_page.clicked.connect(lambda: ui.show_images_list(-1))
    ui.next_page.clicked.connect(lambda: ui.show_images_list(1))  # 图像列表翻页
    sys.exit(app.exec_())
